// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by beats/dev-tools/cmd/asset/asset.go - DO NOT EDIT.

package tikv

import (
	"github.com/elastic/beats/v7/libbeat/asset"
)

func init() {
	if err := asset.SetFields("filebeat", "tikv", asset.ModuleFieldsPri, AssetTikv); err != nil {
		panic(err)
	}
}

// AssetTikv returns asset data.
// This is the base64 encoded gzipped contents of module/tikv.
func AssetTikv() string {
	return "eJzskz+PnEwMh/v9FD9dc+8baaGniBRduiRSpJwipYpmGQPWDmM0Nsvx7aMhsOJu86dJurhCnrGfBxuOONNcwfh8OQDGFqjC3SO/+3x3ADxpnXgwlljh9QEA8hE+iB8DHQDtJNnXWmLDbQVLY042TMFrtVw/IrqeroAcNg9UoU0yDmvmB5gcD9L3Etd24AjraM8v1pt73p55Ej9fkxvX6Ml2yZ+gc7xB4zgc5ULpO6J4dvwg0RxHxRgHl5Q8elJ1LSlc9KtUgU+djMGDnlgNEsOMqaOIXMKxXRC067y5D/7GfD+x36hf3dbZNUn6ZXof34Kjmos1IUir+1d6Oca9zv2r+2f5zelM8yTJvzj7hVmO99JuYp4ajuS35bphCFy7XFjgsaOFAmlwcWHMg00EFyY3K9QSx7a4af5FRtQuYlSCQxvk5AJqiRdK9l9nNmhVltM0FRScGtdFLWU7sqeSYnkiZ1o2HCg/lb1To1Su1UVnffgfQ5KaVCXBBDpQzc28eN4ucffR/9k1Lj/Bv0X+tUV+CwAA//8L+H2b"
}
