filebeat.inputs:
  - type: filestream
    paths:
      - ./deploy/localtest/test_input_01.log
    parsers:
      - multiline.type: pattern
        multiline.pattern: '^# Time: '
        multiline.negate: true
        multiline.match: after
        multiline.timeout: 1s
    processors:
      - add_fields:
          target: kubernetes
          fields:
            pod:
              name: db-tidb-1
            namespace: tidb1369682775200135353
  - type: filestream
    paths:
      - ./deploy/localtest/test_input_02.log
    parsers:
      - multiline.type: pattern
        multiline.pattern: '^# Time: '
        multiline.negate: true
        multiline.match: after
        multiline.timeout: 1s
    processors:
      - add_fields:
          target: kubernetes
          fields:
            pod:
              name: db-tidb-2
            namespace: tidb1369682775200135351
  - type: filestream
    paths:
      - ./deploy/localtest/test_input_02.log
    parsers:
      - multiline.type: pattern
        multiline.pattern: '^# Time: '
        multiline.negate: true
        multiline.match: after
        multiline.timeout: 1s
    processors:
      - add_fields:
          target: kubernetes
          fields:
            pod:
              name: db-tidb-2
            namespace: tidb1369682775200135350
  - type: filestream
    paths:
      - ./deploy/localtest/test_input_02.log
    parsers:
      - multiline.type: pattern
        multiline.pattern: '^# Time: '
        multiline.negate: true
        multiline.match: after
        multiline.timeout: 1s
    processors:
      - add_fields:
          target: kubernetes
          fields:
            pod:
              name: db-tidb-2
            namespace: tidb1369682775200135337
  - type: filestream
    paths:
      - ./deploy/localtest/test_input_02.log
    parsers:
      - multiline.type: pattern
        multiline.pattern: '^# Time: '
        multiline.negate: true
        multiline.match: after
        multiline.timeout: 1s
    processors:
      - add_fields:
          target: kubernetes
          fields:
            pod:
              name: db-tidb-2
            namespace: tidb1369682775200135336
processors:
  - tidb_slow_query:

output.tidb_slow_query:
  host: tidb.e23bdccc.cb17aaf2.us-west-2.prod.aws.tidbcloud.com
  port: 4000
  user: slowquery
  password: e0guRuL91x%@Qm7cn2TxsOoI
  database: slow_query_dev
  timeout: 60000s
  max_retries: 3
  backoff:
    init: 1s
    max: 10s
  partition:
    retention: 365
    roll_step: 3

path.home: ./__local_home
logging.level: info
logging.metrics.enabled: false
